# ==================================================================
#  tubex-lib - travis test script
# ==================================================================

language: c++
sudo: false

addons:
  apt:
    sources:
    #- deadsnakes
    #- ubuntu-toolchain-r-test
    #- chef-current-precise
    - ubuntu-toolchain-r-test
    - kubuntu-backports
    - deadsnakes
    - george-edison55-precise-backports

    packages:
    - g++-5
    - cmake
    - cmake-data
    - pkg-config
    - libboost-dev
    - libcppunit-dev
    - python3.6
    #- cmake
    #- time
    #- pkg-config
    #- g++-5
    #- libboost-dev
    #- libcppunit-dev # for ibex with cmake
    ##- doxygen # for documentation
    
sudo: required

cache:
  directories:
  #- $HOME/ibex

matrix:
  include:
  #- os: osx
  #  compiler: clang
  - os: linux
    compiler: gcc-5
    env: PYTHON=3.6 CPP_VERSION=11 GCC=5.0
    python: "3.6"

#before_install:
#  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install clang-omp; fi

install:
  - sudo sh ./scripts/ibex/build_IbexLib.sh
  - sudo sh ./scripts/ibex/build_IbexGeometryLib.sh
  #- sudo pip install breathe # for documentation
  #- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/ibex

script:
  #- mkdir make
  #- cd make
  #- if [ $TRAVIS_OS_NAME == osx ]; then
  #    CC=clang-omp CXX=clang-omp++ cmake -DCMAKE_INSTALL_PREFIX=${HOME} -DIBEX_ROOT=${HOME}/ibex -DBUILD_TESTS=ON ../ ;
  #  fi
  #- if [ $TRAVIS_OS_NAME == linux ]; then
  #    cmake -DCMAKE_INSTALL_PREFIX=${HOME} -DIBEX_ROOT=${HOME}/ibex -DCMAKE_CXX_COMPILER=g++-5 -DBUILD_TESTS=ON ../ ;
  #  fi
  #- make
  - ./build.sh
  - cd make
  - make test